// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6TGOcIKjhbiGByaGSaMUR4IqBLwbYbFM',
    appId: '1:1171336226:web:4e4f8ef822cf33d7352e7b',
    messagingSenderId: '1171336226',
    projectId: 'overheard-afa00',
    authDomain: 'overheard-afa00.firebaseapp.com',
    storageBucket: 'overheard-afa00.firebasestorage.app',
    measurementId: 'G-19HDPF20J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQPDAKvbCniVUVnJp9L-5lWq5Sdh8CT90',
    appId: '1:1171336226:android:de57762e87716b8d352e7b',
    messagingSenderId: '1171336226',
    projectId: 'overheard-afa00',
    storageBucket: 'overheard-afa00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASNFin-wqqBl2pn2FZtS2ZeSUT-PXgUGA',
    appId: '1:1171336226:ios:4f03dcdb6a62df33352e7b',
    messagingSenderId: '1171336226',
    projectId: 'overheard-afa00',
    storageBucket: 'overheard-afa00.firebasestorage.app',
    iosBundleId: 'com.example.overheard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASNFin-wqqBl2pn2FZtS2ZeSUT-PXgUGA',
    appId: '1:1171336226:ios:4f03dcdb6a62df33352e7b',
    messagingSenderId: '1171336226',
    projectId: 'overheard-afa00',
    storageBucket: 'overheard-afa00.firebasestorage.app',
    iosBundleId: 'com.example.overheard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6TGOcIKjhbiGByaGSaMUR4IqBLwbYbFM',
    appId: '1:1171336226:web:16996535d126d187352e7b',
    messagingSenderId: '1171336226',
    projectId: 'overheard-afa00',
    authDomain: 'overheard-afa00.firebaseapp.com',
    storageBucket: 'overheard-afa00.firebasestorage.app',
    measurementId: 'G-QJ60338HGG',
  );
}
